export const ERROR_CODES = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    TASK_NOT_FOUND: "TASK_NOT_FOUND",
} as const;